name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: linux
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v8
      - uses: cachix/cachix-action@v6
        with:
          name: korayal-hls
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: nix-build
